name: 'gdrive-upload-action'
description: 'Github Action that uploads files to Google Drive'
author: 'Bonitasoft'

inputs:
  credentials:
    description: 'Google API credentials in Base64 format'
    required: true

outputs:
  TODO:
    description: 'TODO'

runs:
  using: node20
  main: dist/index.js
