name: 'gdrive-upload-action'
description: 'GitHub Action that uploads files to Google Drive.'
author: 'Bonitasoft'

inputs:
  credentials:
    description: 'Google API credentials in base64 format.'
    required: true
  parent-folder-id:
    description: 'The parent folder ID in Google Drive.'
    required: true
  source-filepath:
    description: 'The path of the local file to upload.'
    required: true
  target-filepath:
    description:
      'The remote file path in Google Drive of the uploaded file relative to the
      given parent folder. Use parent folder root with source filename when not
      set.'
  overwrite:
    description: 'Overwrite remote file on Google Drive if it does already exist.'
    default: 'true'
  create-checksum:
    description: 'Create and upload a sha-256 checksum file next to the uploaded file.'
    default: 'false'

outputs:
  file-id:
    description: 'The ID of the uploaded file.'

runs:
  using: node20
  main: dist/index.js
