name: 'gdrive-upload-action'
description: 'GitHub Action that uploads files to Google Drive.'
author: 'Bonitasoft'

inputs:
  credentials:
    description: 'Google API credentials in base64 format.'
    required: true
  parentFolderId:
    description: 'The parent folder ID in Google Drive.'
    required: true
  sourceFilePath:
    description: 'The path of the local file to upload.'
    required: true
  targetFilePath:
    description:
      'The remote file path in Google Drive of the uploaded file relative to the
      given parent folder. Use parent folder root with source filename when not
      set.'
  overwrite:
    description: 'Overwrite remote file on Google Drive if it does already exist.'
    default: 'true'

outputs:
  fileId:
    description: 'The ID of the uploaded file.'

runs:
  using: node20
  main: dist/index.js
